### ISSUE TITLE
`git-hub setup` should be global by default, if no global config exists

### ISSUE THREAD

**Issue by guyhughes** [sociomantic-tsunami/git-hub#159]
Having experienced https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=799286, I propose that `git-hub setup` default to `--global` if there's no global oauth token set; and otherwise it should operate on the local repository by default. 

I'm assuming that most common use case for this awesome tool is where a global config is necessary.

I can see that `setup --global` is similar in design to `git config --global`, but this may be jarring.

:+1:

**Comment by leandro-lucarella-sociomantic** [comment]
I guess that could work. Also it might be helpful to be more explicit about where the config is being stored...

**Comment by salewski** [comment]
First things first: thank you for `git-hub`; it is a very nice tool indeed.

I would like to respectfully request that the existing behavior *not* be changed to global by default. I find the documentation in `git-hub(1)` to be very clear, and the "local unless `--global` or `--system` is specified" approach to be exactly what I would expect because it is analogous to how `git config..` works.

It's true that `git config` supports a `'--local'` option, and I would imagine that a change to `'git hub'` would involve introducing a similar option. However, even with such an option it would be a violation of my expectations that a tool in the `'git'` ecosystem modified my `'~/.gitconfig'` file unless I explicitly requested it to.

**Comment by llucax** [comment]
Being `setup` an interactive command already, we could just ask the user if they want to save the oauth token globally if there is no global oauth token already...
On the other hand, I like keeping things simple unless the complexity is really needed, and in this case I'm still not very convinced it is (you can get the setup command wrong once, then you learn from your mistake and I guess it will hardly be a problem again)...

Just adding a message saying "salving configuration to ..." might be enough to alert the user about what's going on...

**Comment by guyhughes** [comment]
Looking at the `git-hub(1)` manpage, my feeble mind does not clue in about the `setup` command acting locally.

To keep the best ux for local config use cases, I think that your suggestion @llucax to add a message to say which config is being targeted would resolve the concern raised originally.

**Comment by llucax** [comment]
Let me know what do you think about #159.

**Comment by llucax** [comment]
Arrghh, I mean #180.

**Comment by llucax** [comment]
Due to the lack of activity, I will assume #180 was enough of improvement. Also other people were concerned about the lack of consistency if there is any guessing when choosing what configuration to touch. So I'm closing this. Feel free to reopen if you don't agree.
