### ISSUE TITLE
Create with label and assignees

### ISSUE THREAD

**Issue by nomeata** [sociomantic-tsunami/git-hub#263]
I find that in order to have a pure command line interface, I need to be able to set labels and assignees on new pull requests that create.

Would it be possible to add  `--label` and `--assign` options to `git hub pull new`?

**Comment by nomeata** [comment]
I guess there is `git hub pull update` that can do that already, so hopefully integrating that into `git hub pull new` wouldn’t be hard?

**Comment by leandro-lucarella-sociomantic** [comment]
This is probably a long-unnoticed bug. As the original intention is that `pull new` is just an extension of `issue new`, and `issue new` can set labels and assignee.

**Comment by leandro-lucarella-sociomantic** [comment]
OK, so it turns out it's not as easy as it looked like and it's probably not a bug. Well, it's actually not hard, but it is not directly supported by GitHub API, when creating a PR via the API you can't set the milestone, assignee or labels (https://developer.github.com/v3/pulls/#create-a-pull-request). But we can create the PR and then update it as part of the same `pull new` command.

**Comment by leandro-lucarella-sociomantic** [comment]
@nomeata can you try #264 out and let me know if it works for you?

**Comment by nomeata** [comment]
Yup, worked for me :-)

**Comment by leandro-lucarella-sociomantic** [comment]
BTW, I made a release candidate for v1.1.0 (the last minor release was more than 1.5 years ago so it's a good time for a new one even if we don't have that many new features). Can you please check it out?

If I don't get any bad news in the following few days, I will do the final release.
