### ISSUE TITLE
issue new: Error reading template from path '…/.github/ISSUE_TEMPLATE': [Errno 21] Is a directory

### ISSUE THREAD

**Issue by jwilk** [sociomantic-tsunami/git-hub#310]
`git hub issue new` doesn't handle `.github/ISSUE_TEMPLATE` directories correctly:

```console
$ git clone -q https://github.com/pypa/pypi-support
$ cd pypi-support
$ find .github/ISSUE_TEMPLATE
.github/ISSUE_TEMPLATE
.github/ISSUE_TEMPLATE/mass-name-squatter.yml
.github/ISSUE_TEMPLATE/account-recovery.yml
.github/ISSUE_TEMPLATE/limit-request-file.yml
.github/ISSUE_TEMPLATE/limit-request-project.yml
.github/ISSUE_TEMPLATE/access-issues.yml
.github/ISSUE_TEMPLATE/pep541-request.yml
.github/ISSUE_TEMPLATE/config.yml
$ git config hub.upstream pypa/pypi-support
$ git hub issue new
Error: Error reading template from path '/home/jwilk/pypi-support/.github/ISSUE_TEMPLATE': [Errno 21] Is a directory: '/home/jwilk/pypi-support/.github/ISSUE_TEMPLATE'
```

Work-around: use `--no-template`.

**Comment by llucax** [comment]
Mmm, not good. A quick and easy fix would be to just ignore the template if it is a directory. Then we could add some prompt yo pick which template to use as an enhancement.

@daniel-zullo since you implantes this, if you have some time could you have a look to implemente the quick fix? I know time is scarce.

**Comment by daniel-zullo** [comment]
My bad...I'll have a look later today

**Comment by llucax** [comment]
Probably not, I think the possibility to have more than one template wasn't always there...
